### PR TITLE
Reset board before `set_fen_position`

### LINKED ISSUE #13: set_fen_position does not reset board
Using the set_fen_position method does not reset the board as it should according to [the UCI protocol](http://wbec-ridderkerk.nl/html/UCIProtocol.html).

### PR DESCRIPTION
**Pull request by charlesoblack**
This PR makes `set_fen_position` reset the board before setting the FEN position. As per the UCI protocol, this should be done by putting `ucinewgame` to the engine.

This closes #13 .

I've also included a test for this. Please let me know if you want anything else!

### CODE REVIEW

**Comment by charlesoblack** [comment]
Looks like the Travis worker is failing, but I think the tests should pass just fine. :)

**Comment by zhelyabuzhsky** [comment]
> Looks like the Travis worker is failing, but I think the tests should pass just fine. :)

Please, reformat your code with `$ black .` and everything will be fine =)

**Comment by charlesoblack** [comment]
It seems like it passes `black`:

[online black](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AJhAT1dAD2IimZxl1N_Wk6tt2q7MPb5h5eRNNX0jzxtxWsocH9VydBDeZ8_IOBUxrHRkjNu3paE-uDGWezurdE2B96w6CdNnXxEcge4Tpt2hahk6aKd432AqDLNd2J_EjmW0TnGuAE8mj7KKd8ix-VHuTG_gV2f3AS0OmtZrjDnlbcFdwYgZSSjBUqVdLK605djxR1QSMtMo-4hZNGwcFRO8xaHG-b_qWSeTufm2W9V80nRu7vFuj0hjp8HJggtmFv95p_3FKTzUozSGb7eEwy2cahB_r8ESBlnnJYPwNzeiZvpntmkOglYAEVQaGVTaj2TKr6-M8UxFOsXNpUq5ewTAyOijyQAKfpETTPXQsTYMQ3FlYVYLRyRJhXmOQoeS0unh0oV7vClWp_x-BOLv-MUCb2TGXOTpU9U8WyafFbnCCMAAAAAACaoFqLkHtI9AAHZAuIEAAA169v3scRn-wIAAAAABFla)

**Comment by zhelyabuzhsky** [comment]
> It seems like it passes `black`


No =)

https://travis-ci.org/zhelyabuzhsky/stockfish/builds/593704389#L263

Just reformat with local black:

```bash
$ pip install black
$ black .
```

**Comment by charlesoblack** [comment]
lol. I truly do not understand `black`. Seems like a silly thing to me since it ends up being inconsistent with the above line.

Either way, it should pass now.

**Comment by zhelyabuzhsky** [comment]
Well done =) Thank you for your merge request!

**Comment by charlesoblack** [comment]
Thank you for merging the PR and being so patient with me and `black`! :)

**Pull request merged**
