### PR TITLE
Added column labels in get_board_visual 

### PR DESCRIPTION
**Pull request by JanFranchini**
Stockfish board output has an extra line with column labels that is cut out by get_board_visual.

### CODE REVIEW

**Review by zhelyabuzhsky — CHANGES_REQUESTED** [review]
Hello @JanFranchini 

Thank you for your contribution )

Please fix the problems in the tests and I will gladly merge your PR

**Comment by JanFranchini** [comment]
Hello @zhelyabuzhsky,
tests failure seems to be caused by an older Stockfish version used for testing. This different output format has been introduced in v12 and with v14.1 the new board parser works fine. Do we need backward compatibility for Stockfish v11 and previous? In case, i can add some checks.

By the way, even just running tests in this repo with Stockfish v14.1 fails with this error: 
```FAILED tests/stockfish/test_models.py::TestStockfish::test_set_skill_level - AssertionError: assert 'c2c4' in ('b2b3', 'b2b3', 'd2d3', 'd2d4', 'b1c3', 'd1e2', ...)```

Instead, if i run tests with the stockfish installed with ```sudo apt-get install stockfish``` no fails occurs.  

Don't know if i messing up with something.

**Comment by zhelyabuzhsky** [comment]
> Instead, if i run tests with the stockfish installed with `sudo apt-get install stockfish` no fails occurs.

It's Ubuntu? Which version?

**Comment by JanFranchini** [comment]
> It's Ubuntu? Which version? 21.10?
> 
I'm on Ubuntu 20.04.

> You can add `'c2c4'` to this list to correct the test.
>
I've found some other moves that were not expected in tests, so i added them.

**Review by zhelyabuzhsky — APPROVED** [review]

**Comment by zhelyabuzhsky** [comment]
@JanFranchini well done, thank you

**Pull request merged**
