### PR TITLE
Added time parameter to Stockfish#get_evaluation

### PR DESCRIPTION
**Pull request by rinslow**
So you can get the evaluation with a time limit :) useful for research

### CODE REVIEW

**Comment by kieferro** [comment]
Hi @rinslow, thank you for your contribution to the project.

This project is no longer maintained in this repo but on [this fork](https://github.com/py-stockfish/stockfish). (More information about this can be found [here](https://github.com/zhelyabuzhsky/stockfish/issues/130)).

We are in the process of transferring the PRs to the fork one by one. This PR would be the next one. That's why we would be very happy if you could close the PR on this repo and open it again for the fork. A small addition to the README for the new functionality added by the PR would be awesome as well. We will then review and merge. Thanks.

**Comment by kieferro** [comment]
@rinslow I wanted to ask again about the status of this PR. If you don't have time/possibility to reopen the PR in the other repo at the moment, that's not a problem. And if you'd rather have us take care of the PR, that's not a problem either. But please just let us know so we can plan.
Thanks

**Comment by rinslow** [comment]
Hey, sorry for the delayed response
I would love if you could merge this into the fork as I don't have that much free time atm. 
Thanks!

**Comment by kieferro** [comment]
Okay, thanks @rinslow. We'll take care of it

**Comment by kieferro** [comment]
Implemented via https://github.com/py-stockfish/stockfish/pull/61. Please close this PR so that we can keep track of which PRs are not yet implemented on the fork

**Pull request closed without merging**
