### PR TITLE
fix unique parameter issue for multiple objects

### PR DESCRIPTION
**Pull request by VivekThazhathattil**
Hi,
This is a fix for issue #59 " Parameters not unique for objects". 
I've also included a member function to reset the parameters, which I thought was handy. :)

### CODE REVIEW

**Comment by mickkn** [comment]
Looks like a legit fix, could you include the test in the pull request?

**Comment by VivekThazhathattil** [comment]
Should I include tests for both `reset_parameter` function and for 'unique parameter for 2 objects' cases?

**Comment by VivekThazhathattil** [comment]
Closes #59

**Comment by zhelyabuzhsky** [comment]
Thank you very much @VivekThazhathattil

**Pull request merged**
